apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/
  - transformer-secret.yaml

replicas:
  - name: nginx-deployment-epc
    count: 1

configMapGenerator:
  - name: transformer-html-configmap
    literals:
      - endpoint="transformer.example.com"