apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db
  namespace: default
spec:
  encryptedData:
    password: AgBb/Ec6ZKnuQDkPgoGc1EGZOT/3KGgpvhnEWSJATDLtrzpbh2tCPqInfk6qy9F+binnxCYJpnzqf0YnxQvZpxVNgjMqBF1LhTjZjjCcfDXcdJec2DCSYQmjofz/O2nlmVOwoGIGTvsHDjT9G1oerfhcGhxhbRhb5Fe8hn6HRMVrbQ2wJVRW5nVOtdVV1/YYGW+XJF+9/1Ud9To/uDb/g8lhhejvmHtEGJ8zy7I5WzuvPmfmKBOivvC1C3KbG5tyDA1tUs3rrckOshqmZAvBYwN7rjRSX//b3Naaj8vtKWX8Fv3TcFptIsnXlt7EirE67dGMorW8GueUcFw3niPRIecSeVlzpqP5CTVIkpq4mBDAkBXU0h2DDzt7+P4rlTrXuM45EtTffsTwFO1T6aeC692I7+oG5vNS1qsgaN60xdPhxJH3QWXxTheKYQjMLuJXV+WRjOjXg8brW7+wHBtIWVZOq6DNo1DigzQLBUTM/bdZ0BFin3vgh9vaHGICoSHnoSyv5VU0M+I6XPHLpaWsK6lJTIa3zLmQNMH3lrwiv5S78blCeDpuUFJMLCOdCcbKHaZ8nEX/FUmeuM/DRN8v4UdvthB0aUA0ZABaSXt9IoVcktkFAyCkM7tdu0nfG/LNfXvFY9cu5froYHSJjIemFNfp1VwkCfPvVzkIYk5IGPihluRB7PjqgMxZGHNUXr6nyCCFV5Lgu6if4UejEyD89N8=
  template:
    metadata:
      creationTimestamp: null
      name: db
      namespace: default