apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-epc
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: registry.h2o-3-24072.h2o.vmware.com/digit/nginx:1.0.7
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        securityContext:
          capabilities:
            drop: ["ALL"]
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          runAsGroup: 1000
          runAsNonRoot: true
          runAsUser: 999
