apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/
  - pve-secret.yaml

replicas:
  - name: nginx-deployment-epc
    count: 3
commonLabels:
  team: pve

configMapGenerator:
  - name: pve-configmap
    literals:
      - endpoint="pve.example.com"