apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db
  namespace: default
spec:
  encryptedData:
    password: AgCeofWFVQ1v7l7/FS+Uclk3xvzMkb6B3aqgsrarRfOsNwYDAaZO9YN+hPJT6px99w86Ud9Zi1Bwb33Os845H3YU8SghGIom5/AWm8l3pTet6qnItEl3hUglNKLA8CLsvuOa03PEs/F9FFraOvg55xgvI7FGbicxahsiuettRKQlmyZKZ673Q6RINGkQXnxvFuJaUd4EEW9XDdCzZdhUkwte2Co7N7VZktHgz8RrE3wq+Yx4B1XmskXrKi2TLGvY8nU2g1dhQKlK1gGUM6byJ88fbt0JD+wA8MaUau2E2nHckKQKMzGkWGTjoQpSQBV7RHj3uA9P9+8o5oUdGTyei6ih4gujYwPG1w9hgix2YREs6nUIGr5oTDRVHPbJoA4aph5VTEoxlgFtTCPEnnCy31XW/HxITj1MxCFkeV3QkKYGEx5GWxVdiY8vvOfQsCm8pcmwOdVxyOyxmu60yLu94BYhbAvQWHlFN+rywm5ef8w5h2lHiIbXjR45zvRLgSoFbBfxIP/UmFJ/B2cTMlrelXvfvoHbCAnzsSFAPyYd0ceo0Jga5yaPO2IQcYo4d/lLwlhMGGTQ8MbkXUCwPMFNtMjatKUquL/1G6YKr8w2wPVLxcyi0jwgOLV0CDteN7AWZLtfM/nglKsPdVJWknefMLqvlK+uc1HEZyqG/FfpoI1D5Pr0m/jbxTbQFhvqn59ZM0s2Vdif8rsN
  template:
    metadata:
      creationTimestamp: null
      name: db
      namespace: default
    type: Generic